version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/mobile"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    expo:
      patterns:
      - "expo"
      - "expo-*"
      - "@expo/*"
      - "react-native*"
      - "@types/react"
